/* Formatted on 29.1.2016 18:12:07 (QP5 v5.252.13127.32867) */
  SELECT DISTINCT (ATC.TABLE_NAME), COUNT (ATC.COLUMN_NAME)
    FROM USER_TAB_COLS ATC
         INNER JOIN USER_TABLES ATB ON ATC.TABLE_NAME = ATB.TABLE_NAME
   WHERE ATC.VIRTUAL_COLUMN = 'NO' AND ATC.HIDDEN_COLUMN = 'NO'
GROUP BY ATC.TABLE_NAME
ORDER BY ATC.TABLE_NAME;