SELECT 
ATC.TABLE_NAME,ATC.COLUMN_NAME,ATC.DATA_TYPE
--ATC.* 
FROM ALL_TAB_COLS ATC
INNER JOIN ALL_TABLES ATB ON ATC.TABLE_NAME=ATB.TABLE_NAME 
WHERE 
ATC.OWNER='ISKUR'
ORDER BY 
ATC.TABLE_NAME, ATC.COLUMN_ID;