/* Formatted on 29.1.2016 18:12:14 (QP5 v5.252.13127.32867) */
  SELECT ATC.TABLE_NAME, ATC.COLUMN_NAME, ATC.DATA_TYPE
    FROM USER_TAB_COLS ATC
         INNER JOIN USER_TABLES ATB ON ATC.TABLE_NAME = ATB.TABLE_NAME
   WHERE ATC.VIRTUAL_COLUMN = 'NO' AND ATC.HIDDEN_COLUMN = 'NO'
ORDER BY ATC.TABLE_NAME, ATC.COLUMN_ID;