/* Formatted on 14.1.2016 14:34:20 (QP5 v5.252.13127.32867) */
  SELECT COLS.TABLE_NAME,
         COLS.COLUMN_NAME,
         COLS.POSITION,
         CONS.VALIDATED,
         CONS.STATUS,
         CONS.OWNER
    FROM ALL_CONSTRAINTS CONS
         INNER JOIN ALL_CONS_COLUMNS COLS
            ON CONS.CONSTRAINT_NAME = COLS.CONSTRAINT_NAME AND CONS.OWNER = COLS.OWNER
   WHERE     --COLS.TABLE_NAME = 'TABLE_NAME' AND
             CONS.CONSTRAINT_TYPE = 'P'
         
         AND UPPER(CONS.STATUS) = 'ENABLED'
         AND UPPER(CONS.OWNER) = 'ISKUR'
         AND COLS.TABLE_NAME NOT LIKE '%$%'
ORDER BY COLS.TABLE_NAME, COLS.POSITION;